#!/usr/bin/env bash

cd "$(dirname "$0")"

# turn on verbose debugging output for parabuild logs.
exec 4>&1; export BASH_XTRACEFD=4; set -x

# make errors fatal
set -e

# bleat on references to undefined shell variables
set -u

# Check autobuild is around or fail
if [ -z "$AUTOBUILD" ] ; then
    exit 1
fi

if [ "$OSTYPE" = "cygwin" ] ; then
    autobuild="$(cygpath -u $AUTOBUILD)"
else
    autobuild="$AUTOBUILD"
fi

top="$(pwd)"
stage="$(pwd)/stage"

# load autobuild provided shell functions and variables
source_environment_tempfile="$stage/source_environment.sh"
mkdir -p "$stage"
"$autobuild" source_environment > "$source_environment_tempfile"
. "$source_environment_tempfile"

# remove_cxxstd
source "$(dirname "$AUTOBUILD_VARIABLES_FILE")/functions"

# The name of the directory that `autobuild install` drops the cef-bin
# package into -- matches Dullahan's own build-cmd.sh naming exactly (see
# its own comment: no way to share this name between CEF and its consumers,
# so it has to be kept in lock step manually). Same cef-bin installable,
# same directory name.
cef_no_wrapper_dir="$stage/packages/cef"
cef_no_wrapper_build_dir="$cef_no_wrapper_dir/build"

case "$AUTOBUILD_PLATFORM" in
    windows*)
        load_vsvars

        # build the CEF c->C++ wrapper "libcef_dll_wrapper", same as Dullahan
        cd "$cef_no_wrapper_dir"
        rm -rf "$cef_no_wrapper_build_dir"
        mkdir -p "$cef_no_wrapper_build_dir"
        cd "$cef_no_wrapper_build_dir"
        cmake -G "$AUTOBUILD_WIN_CMAKE_GEN" -A "$AUTOBUILD_WIN_VSPLATFORM" \
              -DCMAKE_CXX_FLAGS="$LL_BUILD_RELEASE" \
              $(cmake_cxx_standard $LL_BUILD_RELEASE) \
              -DCEF_RUNTIME_LIBRARY_FLAG=-MD -DUSE_SANDBOX=Off ..
        cmake --build . --config Release --target libcef_dll_wrapper --parallel $AUTOBUILD_CPU_COUNT

        # generate the project files for llcefbrowser, pointing it at the
        # already-staged cef-bin package rather than triggering its own
        # FetchContent download (CEF_PACKAGE_DIR, not CEF_PACKAGE_URL --
        # both are already supported by the existing CMakeLists.txt)
        cd "$stage"
        cmake "$(cygpath -m "$top")" \
            -G "$AUTOBUILD_WIN_CMAKE_GEN" -A "$AUTOBUILD_WIN_VSPLATFORM" \
            -DCEF_PACKAGE_DIR="$(cygpath -m "$cef_no_wrapper_dir")" \
            -DCMAKE_CXX_FLAGS="$LL_BUILD_RELEASE" \
            $(cmake_cxx_standard $LL_BUILD_RELEASE)

        cmake --build . --config Release --target llcefbrowser --parallel $AUTOBUILD_CPU_COUNT

        # prepare the staging dirs
        cd "$top"
        mkdir -p "$stage/include/llcefbrowser"
        mkdir -p "$stage/lib/release"
        mkdir -p "$stage/LICENSES"

        # llcefbrowser's own public headers
        cp "$top/include/"*.h "$stage/include/llcefbrowser/"

        # llcefbrowser's own library only. Deliberately NOT staging/packaging
        # libcef.lib/libcef_dll_wrapper.lib or any CEF runtime files
        # (bin/release/*, resources/*) here -- nothing in the viewer links
        # llcefbrowser yet (this package is groundwork for the future
        # in-viewer CEF producer), and the viewer already installs the
        # identical CEF distribution's libs/runtime via the "dullahan"
        # package for the legacy media plugin; packaging the same files
        # again here just collides with that install (autobuild refuses two
        # packages writing the same path). A future consumer of this
        # package should also depend on ll::cef (CEFPlugin.cmake) to get
        # those shared CEF libraries -- see EmbeddedBrowser.cmake.
        cp "$stage/Release/llcefbrowser.lib" "$stage/lib/release/"

        # license -- namespaced (not just LICENSES/LICENSE) to avoid
        # colliding with some other already-installed package using that
        # same generic name
        cp "$top/LICENSE" "$stage/LICENSES/llcefbrowser_LICENSE.txt"

        # populate version_file -- llCefBrowserVersion.h is generated by the
        # top-level CMake configure step above from git + CEF version info
        # (LLCEFBROWSER_VERSION_MAJOR/MINOR + git commit count/hash), so just
        # read those back out rather than re-deriving anything
        ver_major="$(grep -oE 'LLCEFBROWSER_VERSION_MAJOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        ver_minor="$(grep -oE 'LLCEFBROWSER_VERSION_MINOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        echo "${ver_major}.${ver_minor}.0" > "$stage/VERSION.txt"
    ;;
    darwin*|linux*)
        # Not yet built/tested on this platform -- windows64 is the only
        # platform actually exercised by the embedded-browser project so far.
        exit 1
    ;;
esac
