#!/usr/bin/env bash

cd "$(dirname "$0")"

# turn on verbose debugging output for parabuild logs.
exec 4>&1; export BASH_XTRACEFD=4; set -x

# make errors fatal
set -e

# bleat on references to undefined shell variables
set -u

# Check autobuild is around or fail
if [ -z "$AUTOBUILD" ] ; then
    exit 1
fi

if [ "$OSTYPE" = "cygwin" ] ; then
    autobuild="$(cygpath -u $AUTOBUILD)"
else
    autobuild="$AUTOBUILD"
fi

top="$(pwd)"
stage="$(pwd)/stage"

# load autobuild provided shell functions and variables
source_environment_tempfile="$stage/source_environment.sh"
mkdir -p "$stage"
"$autobuild" source_environment > "$source_environment_tempfile"
. "$source_environment_tempfile"

# remove_cxxstd
source "$(dirname "$AUTOBUILD_VARIABLES_FILE")/functions"

# The name of the directory that `autobuild install` drops the cef-bin
# package into -- matches Dullahan's own build-cmd.sh naming exactly (see
# its own comment: no way to share this name between CEF and its consumers,
# so it has to be kept in lock step manually). Same cef-bin installable,
# same directory name.
cef_no_wrapper_dir="$stage/packages/cef"
cef_no_wrapper_build_dir="$cef_no_wrapper_dir/build"

case "$AUTOBUILD_PLATFORM" in
    windows*)
        load_vsvars

        # build the CEF c->C++ wrapper "libcef_dll_wrapper", same as Dullahan
        cd "$cef_no_wrapper_dir"
        rm -rf "$cef_no_wrapper_build_dir"
        mkdir -p "$cef_no_wrapper_build_dir"
        cd "$cef_no_wrapper_build_dir"
        cmake -G "$AUTOBUILD_WIN_CMAKE_GEN" -A "$AUTOBUILD_WIN_VSPLATFORM" \
              -DCMAKE_CXX_FLAGS="$LL_BUILD_RELEASE" \
              $(cmake_cxx_standard $LL_BUILD_RELEASE) \
              -DCEF_RUNTIME_LIBRARY_FLAG=-MD -DUSE_SANDBOX=Off ..
        cmake --build . --config Release --target libcef_dll_wrapper --parallel $AUTOBUILD_CPU_COUNT

        # generate the project files for llcefbrowser, pointing it at the
        # already-staged cef-bin package rather than triggering its own
        # FetchContent download (CEF_PACKAGE_DIR, not CEF_PACKAGE_URL --
        # both are already supported by the existing CMakeLists.txt)
        cd "$stage"
        cmake "$(cygpath -m "$top")" \
            -G "$AUTOBUILD_WIN_CMAKE_GEN" -A "$AUTOBUILD_WIN_VSPLATFORM" \
            -DCEF_PACKAGE_DIR="$(cygpath -m "$cef_no_wrapper_dir")" \
            -DCMAKE_CXX_FLAGS="$LL_BUILD_RELEASE" \
            $(cmake_cxx_standard $LL_BUILD_RELEASE)

        cmake --build . --config Release --target llcefbrowser --parallel $AUTOBUILD_CPU_COUNT

        # prepare the staging dirs
        cd "$top"
        mkdir -p "$stage/include/llcefbrowser"
        mkdir -p "$stage/lib/release"
        mkdir -p "$stage/bin/release"
        mkdir -p "$stage/resources/locales"
        mkdir -p "$stage/LICENSES"

        # llcefbrowser's own public headers
        cp "$top/include/"*.h "$stage/include/llcefbrowser/"

        # llcefbrowser's own library, plus (since 2026-09) libcef.lib/
        # libcef_dll_wrapper.lib and the full CEF runtime (bin/release/*,
        # resources/*) -- this package is now self-sufficient and no longer
        # relies on the viewer separately installing the "dullahan" package
        # for those shared pieces (the viewer's own EmbeddedBrowser.cmake no
        # longer depends on it either -- see that file). Safe to package
        # these paths directly now: nothing else in a normal viewer build
        # writes to them any more, so there's no autobuild same-path
        # collision to avoid (the reason this used to be skipped).
        cp "$stage/Release/llcefbrowser.lib" "$stage/lib/release/"
        cp "$cef_no_wrapper_dir/Release/libcef.lib" "$stage/lib/release/"
        cp "$cef_no_wrapper_build_dir/libcef_dll_wrapper/Release/libcef_dll_wrapper.lib" "$stage/lib/release/"

        cp "$cef_no_wrapper_dir/Release/"*.dll "$stage/bin/release/"
        cp "$cef_no_wrapper_dir/Release/v8_context_snapshot.bin" "$stage/bin/release/"
        cp "$cef_no_wrapper_dir/Release/vk_swiftshader_icd.json" "$stage/bin/release/"

        cp "$cef_no_wrapper_dir/Resources/"*.pak "$stage/resources/"
        cp "$cef_no_wrapper_dir/Resources/icudtl.dat" "$stage/resources/"
        cp "$cef_no_wrapper_dir/Resources/locales/"*.pak "$stage/resources/locales/"

        # license -- namespaced (not just LICENSES/LICENSE) to avoid
        # colliding with some other already-installed package using that
        # same generic name
        cp "$top/LICENSE" "$stage/LICENSES/llcefbrowser_LICENSE.txt"

        # populate version_file -- llCefBrowserVersion.h is generated by the
        # top-level CMake configure step above from git + CEF version info
        # (LLCEFBROWSER_VERSION_MAJOR/MINOR + git commit count/hash), so just
        # read those back out rather than re-deriving anything
        ver_major="$(grep -oE 'LLCEFBROWSER_VERSION_MAJOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        ver_minor="$(grep -oE 'LLCEFBROWSER_VERSION_MINOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        echo "${ver_major}.${ver_minor}.0" > "$stage/VERSION.txt"
    ;;
    darwin64)
        export MACOSX_DEPLOYMENT_TARGET="$LL_BUILD_DARWIN_DEPLOY_TARGET"

        # CEF's own bundled cmake macros need a single PROJECT_ARCH, not a
        # universal build (see CMakeLists.txt's own comment) -- build each
        # arch separately with its own Xcode-generator configure, same
        # per-arch-then-lipo pattern Dullahan used for this exact problem
        # before this library replaced it. Each arch's own installed cef-bin
        # package lives directly at $cef_no_wrapper_dir/x86_64 or /arm64
        # (confirmed empirically against a real `autobuild install`, not
        # assumed from the raw package's own archive layout).
        for arch in x86_64 arm64; do
            arch_build_dir="$stage/build_$arch"
            rm -rf "$arch_build_dir"

            cmake -S "$top" -B "$arch_build_dir" -G Xcode \
                -DPROJECT_ARCH="$arch" \
                -DCEF_PACKAGE_DIR="$cef_no_wrapper_dir/$arch" \
                -DUSE_SANDBOX=Off \
                -DLLCEFBROWSER_BUILD_EXAMPLES=OFF

            cmake --build "$arch_build_dir" --config Release --target llcefbrowser --parallel $AUTOBUILD_CPU_COUNT
            for helper_target in llcefbrowser_host llcefbrowser_host_alerts llcefbrowser_host_gpu \
                                  llcefbrowser_host_plugin llcefbrowser_host_renderer; do
                cmake --build "$arch_build_dir" --config Release --target "$helper_target" --parallel $AUTOBUILD_CPU_COUNT
            done
        done

        # prepare the staging dirs
        mkdir -p "$stage/include/llcefbrowser"
        mkdir -p "$stage/lib/release"
        mkdir -p "$stage/LICENSES"

        # llcefbrowser's own public headers
        cp "$top/include/"*.h "$stage/include/llcefbrowser/"

        # llcefbrowser's own library + the CEF wrapper, lipo'd into universal
        # binaries from the two single-arch builds above
        lipo -create -output "$stage/lib/release/libllcefbrowser.a" \
            "$stage/build_x86_64/Release/libllcefbrowser.a" \
            "$stage/build_arm64/Release/libllcefbrowser.a"
        lipo -create -output "$stage/lib/release/libcef_dll_wrapper.a" \
            "$stage/build_x86_64/_deps/cef_prebuild-build/libcef_dll_wrapper/Release/libcef_dll_wrapper.a" \
            "$stage/build_arm64/_deps/cef_prebuild-build/libcef_dll_wrapper/Release/libcef_dll_wrapper.a"

        # the 5 helper .app bundles -- each one's own Info.plist is already
        # correct from either arch's build (not arch-specific), so copy one
        # wholesale and then lipo just the inner Mach-O binary
        for app_name in "llCefBrowserHost" "llCefBrowserHost (Alerts)" "llCefBrowserHost (GPU)" \
                        "llCefBrowserHost (Plugin)" "llCefBrowserHost (Renderer)"; do
            cp -R "$stage/build_x86_64/Release/$app_name.app" "$stage/lib/release/"
            lipo -create \
                "$stage/build_x86_64/Release/$app_name.app/Contents/MacOS/$app_name" \
                "$stage/build_arm64/Release/$app_name.app/Contents/MacOS/$app_name" \
                -output "$stage/lib/release/$app_name.app/Contents/MacOS/$app_name"
        done

        # the CEF framework itself -- a single self-contained bundle (see
        # CMakeLists.txt's own comment on why there's no separate binary/
        # resource file manifest to iterate on macOS), lipo'd the same way
        # Dullahan did for the same framework. Lives directly under each
        # arch's own installed cef-bin package (FetchContent's SOURCE_DIR
        # form uses that directory in place -- no separate "-src" copy of
        # its own the way a URL-fetched FetchContent dependency would get).
        cp -R "$cef_no_wrapper_dir/x86_64/Release/Chromium Embedded Framework.framework" \
            "$stage/lib/release/"
        lipo -create \
            "$cef_no_wrapper_dir/x86_64/Release/Chromium Embedded Framework.framework/Chromium Embedded Framework" \
            "$cef_no_wrapper_dir/arm64/Release/Chromium Embedded Framework.framework/Chromium Embedded Framework" \
            -output "$stage/lib/release/Chromium Embedded Framework.framework/Chromium Embedded Framework"
        lipo -create \
            "$cef_no_wrapper_dir/x86_64/Release/Chromium Embedded Framework.framework/Libraries/libcef_sandbox.dylib" \
            "$cef_no_wrapper_dir/arm64/Release/Chromium Embedded Framework.framework/Libraries/libcef_sandbox.dylib" \
            -output "$stage/lib/release/Chromium Embedded Framework.framework/Libraries/libcef_sandbox.dylib"
        lipo -create \
            "$cef_no_wrapper_dir/x86_64/Release/Chromium Embedded Framework.framework/Libraries/libvulkan.dylib" \
            "$cef_no_wrapper_dir/arm64/Release/Chromium Embedded Framework.framework/Libraries/libvulkan.dylib" \
            -output "$stage/lib/release/Chromium Embedded Framework.framework/Libraries/libvulkan.dylib"
        lipo -create \
            "$cef_no_wrapper_dir/x86_64/Release/Chromium Embedded Framework.framework/Libraries/libvk_swiftshader.dylib" \
            "$cef_no_wrapper_dir/arm64/Release/Chromium Embedded Framework.framework/Libraries/libvk_swiftshader.dylib" \
            -output "$stage/lib/release/Chromium Embedded Framework.framework/Libraries/libvk_swiftshader.dylib"
        # arm64's own v8 snapshot blob, needed alongside x86_64's (already
        # copied wholesale above) for the universal framework to run on
        # either architecture -- same approach Dullahan used.
        cp "$cef_no_wrapper_dir/arm64/Release/Chromium Embedded Framework.framework/Resources/v8_context_snapshot.arm64.bin" \
            "$stage/lib/release/Chromium Embedded Framework.framework/Resources/"

        # license -- namespaced, same convention as the windows64 branch
        cp "$top/LICENSE" "$stage/LICENSES/llcefbrowser_LICENSE.txt"

        # sign the binaries, same conditional-on-real-secrets pattern
        # Dullahan's own build-cmd.sh used for this identical problem --
        # skip gracefully (log only) when run somewhere without them, e.g.
        # this repo's own CI or a developer's local machine.
        CONFIG_FILE="${build_secrets_checkout:-<no build_secrets_checkout>}/code-signing-osx/config.sh"
        if [[ -n "${build_secrets_checkout:-}" && -f "$CONFIG_FILE" ]]; then
            source "$CONFIG_FILE"

            pushd "$stage/lib/release/Chromium Embedded Framework.framework/Libraries"
            for dylib in *.dylib; do
                [ -f "$dylib" ] && codesign --force --timestamp --options runtime --sign "$APPLE_SIGNATURE" "$dylib"
            done
            codesign --force --timestamp --options runtime --sign "$APPLE_SIGNATURE" "../Chromium Embedded Framework"
            popd

            pushd "$stage/lib/release/"
            for app in *.app; do
                [ -d "$app" ] && codesign --force --timestamp --options runtime --sign "$APPLE_SIGNATURE" "$app"
            done
            popd
        else
            echo "No config file $CONFIG_FILE found; skipping codesign."
        fi

        # populate version_file -- llCefBrowserVersion.h is generated by the
        # top-level CMake configure step above (either arch works, both
        # produce the same version numbers), same approach as windows64
        ver_major="$(grep -oE 'LLCEFBROWSER_VERSION_MAJOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        ver_minor="$(grep -oE 'LLCEFBROWSER_VERSION_MINOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        echo "${ver_major}.${ver_minor}.0" > "$stage/VERSION.txt"
    ;;
    linux*)
        # Single arch, no lipo needed (unlike darwin64's universal build) --
        # CEF's own Linux distribution is a flat Release/ + Resources/ dir,
        # much closer in shape to windows64's than darwin64's framework
        # bundle. No separate helper-process executables either: like
        # Windows, Linux re-execs the consuming binary itself for CEF's
        # sub-processes (see CMakeLists.txt's own ExecuteSubProcess() comment
        # on the llcefbrowser target) rather than needing real standalone
        # .app-style helpers the way macOS's sandbox model requires.
        cd "$stage"
        cmake "$top" -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCEF_PACKAGE_DIR="$cef_no_wrapper_dir" \
            -DUSE_SANDBOX=Off \
            -DLLCEFBROWSER_BUILD_EXAMPLES=OFF \
            -DCMAKE_CXX_FLAGS="$LL_BUILD_RELEASE" \
            $(cmake_cxx_standard $LL_BUILD_RELEASE)
        cmake --build . --target llcefbrowser --parallel $AUTOBUILD_CPU_COUNT

        cd "$top"
        mkdir -p "$stage/include/llcefbrowser"
        mkdir -p "$stage/lib/release"
        mkdir -p "$stage/bin/release"
        mkdir -p "$stage/resources/locales"
        mkdir -p "$stage/LICENSES"

        # llcefbrowser's own public headers
        cp "$top/include/"*.h "$stage/include/llcefbrowser/"

        # llcefbrowser's own static library -- lands directly in the (single-
        # config, Ninja) build dir root, unlike Xcode's per-config
        # subdirectory on macOS.
        cp "$stage/libllcefbrowser.a" "$stage/lib/release/"

        # libcef_dll_wrapper is a real CMake target here too (same
        # find_package(CEF)-provided FetchContent mechanism as macOS, not a
        # Darwin-specific thing -- see CMakeLists.txt's own comment), and
        # already built as an llcefbrowser dependency above
        # (add_dependencies(llcefbrowser libcef_dll_wrapper)). Located via
        # find rather than a guessed/hardcoded FetchContent subdirectory
        # path -- there's no Linux machine to verify that path against here,
        # and a loud failure beats silently copying nothing.
        wrapper_lib="$(find "$stage" -name 'libcef_dll_wrapper.a' -print -quit)"
        if [ -z "$wrapper_lib" ]; then
            echo "libcef_dll_wrapper.a not found under $stage after building llcefbrowser" >&2
            exit 1
        fi
        cp "$wrapper_lib" "$stage/lib/release/"

        # CEF runtime binaries + resources -- same CEF_BINARY_FILES/
        # CEF_RESOURCE_FILES manifest CMakeLists.txt's own Linux runtime-copy
        # step uses, copied here too since build-cmd.sh's packaging step
        # (unlike that CMakeLists.txt step, which only stages next to
        # whatever gets built in this same tree) is what actually ends up in
        # the published autobuild package.
        for f in chrome-sandbox libcef.so libEGL.so libGLESv2.so \
                 libvk_swiftshader.so libvulkan.so.1 v8_context_snapshot.bin \
                 vk_swiftshader_icd.json; do
            cp "$cef_no_wrapper_dir/Release/$f" "$stage/bin/release/"
        done

        cp "$cef_no_wrapper_dir/Resources/"*.pak "$stage/resources/"
        cp "$cef_no_wrapper_dir/Resources/icudtl.dat" "$stage/resources/"
        cp "$cef_no_wrapper_dir/Resources/locales/"*.pak "$stage/resources/locales/"

        # license -- namespaced, same convention as the other two platforms
        cp "$top/LICENSE" "$stage/LICENSES/llcefbrowser_LICENSE.txt"

        # populate version_file, same approach as windows64/darwin64
        ver_major="$(grep -oE 'LLCEFBROWSER_VERSION_MAJOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        ver_minor="$(grep -oE 'LLCEFBROWSER_VERSION_MINOR [0-9]+' "$top/include/llCefBrowserVersion.h" | cut -d' ' -f2)"
        echo "${ver_major}.${ver_minor}.0" > "$stage/VERSION.txt"
    ;;
esac
